language: python

os: linux

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a

before_script:
  - conda env create --file prowler_py27.yml
  - conda env create --file prowler_py36.yml

script:
  - source activate prowler_py27
  - pip install nose
  - pip install coverage
  - nosetests --with-coverage --cover-package prowler
  - source activate prowler_py36
  - pip install nose
  - pip install coverage
  - nosetests --with-coverage --cover-package prowler

notifications:
  email:
    - szymon@ibb.waw.pl
