language: python

python:
  - '2.7'
  - '3'

install:
  - python setup.py sdist
  - pip install dist/prwlr-*.tar.gz
  - pip install nose
  - pip install coverage

script:
  - nosetests --with-coverage --cover-package prwlr
  - nosetests --with-coverage --cover-package prwlr

notifications:
  email:
    - szymon@ibb.waw.pl
